export const EJERCICIOS = {
  "Pecho": [
    { nombre: "Press de banca", youtube: "https://youtube.com/watch?v=rT7DgCr-3pg", descripcion: "Ejercicio base para pecho" },
    { nombre: "Press inclinado con barra", youtube: "https://youtube.com/watch?v=DbFgADa2PL8", descripcion: "Pecho superior" },
    { nombre: "Press declinado con barra", youtube: "https://youtube.com/watch?v=LfyQTbFDKSY", descripcion: "Pecho inferior" },
    { nombre: "Press con mancuernas", youtube: "https://youtube.com/watch?v=QsYre__-aro", descripcion: "Rango de movimiento mayor" },
    { nombre: "Aperturas con mancuernas", youtube: "https://youtube.com/watch?v=eozdVDA78K0", descripcion: "Estiramiento del pecho" },
    { nombre: "Aperturas en polea", youtube: "https://youtube.com/watch?v=TAn4psGgEyc", descripcion: "Tensión constante" },
    { nombre: "Fondos en paralelas", youtube: "https://youtube.com/watch?v=2z8JmcrW-As", descripcion: "Pecho y tríceps" },
    { nombre: "Pullover con mancuerna", youtube: "https://youtube.com/watch?v=FK4rHfPuJgo", descripcion: "Expansión torácica" },
    { nombre: "Press en máquina", youtube: "https://youtube.com/watch?v=xUm0BiZCX_I", descripcion: "Seguro para principiantes" },
    { nombre: "Flexiones", youtube: "https://youtube.com/watch?v=IODxDxX7oi4", descripcion: "Sin equipamiento" },
  ],
  "Espalda": [
    { nombre: "Dominadas", youtube: "https://youtube.com/watch?v=eGo4IYlbE5g", descripcion: "Rey de los jalones" },
    { nombre: "Remo con barra", youtube: "https://youtube.com/watch?v=9efgcAjQe7E", descripcion: "Masa en espalda media" },
    { nombre: "Remo con mancuerna", youtube: "https://youtube.com/watch?v=pYcpY20QaE8", descripcion: "Unilateral" },
    { nombre: "Jalón al pecho", youtube: "https://youtube.com/watch?v=CAwf7n6Luuc", descripcion: "Alternativa a dominadas" },
    { nombre: "Remo en polea baja", youtube: "https://youtube.com/watch?v=GZbfZ033f74", descripcion: "Espalda media y baja" },
    { nombre: "Peso muerto", youtube: "https://youtube.com/watch?v=op9kVnSso6Q", descripcion: "Ejercicio global" },
    { nombre: "Peso muerto rumano", youtube: "https://youtube.com/watch?v=JCXUYuzwNrM", descripcion: "Isquiotibiales y espalda baja" },
    { nombre: "Hiperextensiones", youtube: "https://youtube.com/watch?v=ph3pddpKzzw", descripcion: "Espalda baja" },
    { nombre: "Remo en máquina", youtube: "https://youtube.com/watch?v=xQNrFHEMhI4", descripcion: "Seguro y efectivo" },
    { nombre: "Pullover en polea", youtube: "https://youtube.com/watch?v=wMQ8t2gHxGs", descripcion: "Dorsal largo" },
  ],
  "Hombros": [
    { nombre: "Press militar con barra", youtube: "https://youtube.com/watch?v=2yjwXTZQDDI", descripcion: "Hombro completo" },
    { nombre: "Press Arnold", youtube: "https://youtube.com/watch?v=6Z15_WdXmVw", descripcion: "Rotación completa" },
    { nombre: "Press con mancuernas sentado", youtube: "https://youtube.com/watch?v=qEwKCR5JCog", descripcion: "Hombro anterior y medio" },
    { nombre: "Elevaciones laterales", youtube: "https://youtube.com/watch?v=3VcKaXpzqRo", descripcion: "Hombro lateral" },
    { nombre: "Elevaciones frontales", youtube: "https://youtube.com/watch?v=sOoBSE-PrzQ", descripcion: "Hombro anterior" },
    { nombre: "Pájaros", youtube: "https://youtube.com/watch?v=ttvAXDVDlBE", descripcion: "Hombro posterior" },
    { nombre: "Face pulls", youtube: "https://youtube.com/watch?v=rep-qVOkqgk", descripcion: "Manguito rotador" },
    { nombre: "Encogimientos con barra", youtube: "https://youtube.com/watch?v=g6qbq4Lf1FI", descripcion: "Trapecio" },
    { nombre: "Press en máquina", youtube: "https://youtube.com/watch?v=Wqq43dKW1TU", descripcion: "Guiado y seguro" },
    { nombre: "Remo al mentón", youtube: "https://youtube.com/watch?v=OwSuHjTmqHs", descripcion: "Trapecio y hombro" },
  ],
  "Piernas": [
    { nombre: "Sentadilla con barra", youtube: "https://youtube.com/watch?v=ultWZbUMPL8", descripcion: "Reina de los ejercicios" },
    { nombre: "Sentadilla frontal", youtube: "https://youtube.com/watch?v=m4ytaCJZpl0", descripcion: "Cuádriceps dominante" },
    { nombre: "Sentadilla búlgara", youtube: "https://youtube.com/watch?v=2C-uNgKwPLE", descripcion: "Unilateral avanzado" },
    { nombre: "Prensa de piernas", youtube: "https://youtube.com/watch?v=IZxyjW7MPJQ", descripcion: "Cuádriceps y glúteos" },
    { nombre: "Extensiones de cuádriceps", youtube: "https://youtube.com/watch?v=YyvSfVjQeL0", descripcion: "Aislamiento cuádriceps" },
    { nombre: "Curl femoral", youtube: "https://youtube.com/watch?v=1Tq3QdYUuHs", descripcion: "Aislamiento isquiotibiales" },
    { nombre: "Peso muerto rumano", youtube: "https://youtube.com/watch?v=JCXUYuzwNrM", descripcion: "Isquiotibiales y glúteos" },
    { nombre: "Zancadas", youtube: "https://youtube.com/watch?v=D7KaRcUTQeE", descripcion: "Funcional y completo" },
    { nombre: "Hip thrust", youtube: "https://youtube.com/watch?v=xDmFkJxPzeM", descripcion: "Glúteo máximo" },
    { nombre: "Pantorrillas de pie", youtube: "https://youtube.com/watch?v=-M4-G8p1fCI", descripcion: "Gastrocnemio" },
    { nombre: "Pantorrillas sentado", youtube: "https://youtube.com/watch?v=JbyjNymZOt0", descripcion: "Sóleo" },
    { nombre: "Sentadilla sumo", youtube: "https://youtube.com/watch?v=U3HlEF_E9fo", descripcion: "Aductores y glúteos" },
  ],
  "Bíceps": [
    { nombre: "Curl con barra", youtube: "https://youtube.com/watch?v=ykJmrZ5v0Oo", descripcion: "Base del bíceps" },
    { nombre: "Curl con mancuernas", youtube: "https://youtube.com/watch?v=av7-8igSXTs", descripcion: "Rango completo" },
    { nombre: "Curl martillo", youtube: "https://youtube.com/watch?v=TwD-YGVP4Bk", descripcion: "Braquial y braquiorradial" },
    { nombre: "Curl concentrado", youtube: "https://youtube.com/watch?v=Jvj2wV0vOYU", descripcion: "Pico del bíceps" },
    { nombre: "Curl en polea baja", youtube: "https://youtube.com/watch?v=NFzTWp2qpiE", descripcion: "Tensión constante" },
    { nombre: "Curl predicador", youtube: "https://youtube.com/watch?v=fIWP-FRFNU0", descripcion: "Elimina el balanceo" },
    { nombre: "Curl inclinado", youtube: "https://youtube.com/watch?v=soxrZlIl35U", descripcion: "Estiramiento máximo" },
    { nombre: "Curl inverso", youtube: "https://youtube.com/watch?v=nRgxYX2Ve9w", descripcion: "Braquiorradial" },
  ],
  "Tríceps": [
    { nombre: "Press francés", youtube: "https://youtube.com/watch?v=d_KZxkY_0cM", descripcion: "Cabeza larga del tríceps" },
    { nombre: "Extensión en polea alta", youtube: "https://youtube.com/watch?v=2-LAMcpzODU", descripcion: "Aislamiento total" },
    { nombre: "Fondos en paralelas", youtube: "https://youtube.com/watch?v=2z8JmcrW-As", descripcion: "Tríceps y pecho" },
    { nombre: "Patada de tríceps", youtube: "https://youtube.com/watch?v=6SS6K3lAwZ8", descripcion: "Definición" },
    { nombre: "Press cerrado", youtube: "https://youtube.com/watch?v=nEF0bv2FW94", descripcion: "Tríceps con barra" },
    { nombre: "Extensión sobre la cabeza", youtube: "https://youtube.com/watch?v=YbX7Wd8jQ-Q", descripcion: "Cabeza larga" },
    { nombre: "Fondos en banco", youtube: "https://youtube.com/watch?v=0326dy_-CzM", descripcion: "Sin equipamiento" },
    { nombre: "Extensión en polea con cuerda", youtube: "https://youtube.com/watch?v=kiuVA0gs3EI", descripcion: "Separación de cabezas" },
  ],
  "Core": [
    { nombre: "Plancha", youtube: "https://youtube.com/watch?v=pSHjTRCQxIw", descripcion: "Estabilización total" },
    { nombre: "Crunch", youtube: "https://youtube.com/watch?v=Xyd_fa5zoEU", descripcion: "Abdomen superior" },
    { nombre: "Crunch inverso", youtube: "https://youtube.com/watch?v=hyv14_1QMOA", descripcion: "Abdomen inferior" },
    { nombre: "Russian twist", youtube: "https://youtube.com/watch?v=wkD8rjkodUI", descripcion: "Oblicuos" },
    { nombre: "Rueda abdominal", youtube: "https://youtube.com/watch?v=sNyOPxNVDDo", descripcion: "Core completo avanzado" },
    { nombre: "Elevación de piernas", youtube: "https://youtube.com/watch?v=JB2oyawG9KI", descripcion: "Abdomen inferior" },
    { nombre: "Mountain climbers", youtube: "https://youtube.com/watch?v=nmwgirgXLYM", descripcion: "Cardio y core" },
    { nombre: "Dead bug", youtube: "https://youtube.com/watch?v=4XLEnwUr1d8", descripcion: "Estabilización lumbar" },
    { nombre: "Plancha lateral", youtube: "https://youtube.com/watch?v=K2VljzCC16g", descripcion: "Oblicuos" },
    { nombre: "Hollow body", youtube: "https://youtube.com/watch?v=LlDNef_Ztsc", descripcion: "Core funcional" },
  ],
  "Glúteos": [
    { nombre: "Hip thrust", youtube: "https://youtube.com/watch?v=xDmFkJxPzeM", descripcion: "Rey del glúteo" },
    { nombre: "Patada de glúteo", youtube: "https://youtube.com/watch?v=FdWHhItkfko", descripcion: "Aislamiento" },
    { nombre: "Abducción de cadera", youtube: "https://youtube.com/watch?v=MFSKnJg7GU8", descripcion: "Glúteo medio" },
    { nombre: "Sentadilla sumo", youtube: "https://youtube.com/watch?v=U3HlEF_E9fo", descripcion: "Glúteos y aductores" },
    { nombre: "Zancada reversa", youtube: "https://youtube.com/watch?v=xrPteyQLGAo", descripcion: "Glúteo y cuádriceps" },
    { nombre: "Buenos días", youtube: "https://youtube.com/watch?v=YA-h3n9L4YU", descripcion: "Glúteo e isquiotibiales" },
  ],
  "Cardio": [
    { nombre: "Cinta a intervalos", youtube: "https://youtube.com/watch?v=7kgZnJSzROE", descripcion: "HIIT en cinta" },
    { nombre: "Bicicleta estática", youtube: "https://youtube.com/watch?v=RKM8BHjUFXk", descripcion: "Bajo impacto" },
    { nombre: "Remo ergómetro", youtube: "https://youtube.com/watch?v=zQ82RYIFLN4", descripcion: "Cuerpo completo" },
    { nombre: "Salto a la soga", youtube: "https://youtube.com/watch?v=FJmRQ5iTXKE", descripcion: "Coordinación y cardio" },
    { nombre: "Burpees", youtube: "https://youtube.com/watch?v=dZgVxmf6jkA", descripcion: "Funcional intenso" },
    { nombre: "Box jumps", youtube: "https://youtube.com/watch?v=hxldG9FBEAo", descripcion: "Potencia explosiva" },
  ],
}