export const EJERCICIOS = {
  "Pecho": [
    { nombre: "Press de banca", aliases: ["press plano", "banca plana", "press banca"], youtube: "https://youtube.com/watch?v=rT7DgCr-3pg", descripcion: "Ejercicio base para pecho", musculo: "Pecho" },
    { nombre: "Press inclinado con barra", aliases: ["press inclinado", "banca inclinada"], youtube: "https://youtube.com/watch?v=DbFgADa2PL8", descripcion: "Pecho superior", musculo: "Pecho" },
    { nombre: "Press declinado con barra", aliases: ["press declinado", "banca declinada"], youtube: "https://youtube.com/watch?v=LfyQTbFDKSY", descripcion: "Pecho inferior", musculo: "Pecho" },
    { nombre: "Press con mancuernas", aliases: ["press mancuernas", "mancuernas pecho"], youtube: "https://youtube.com/watch?v=QsYre__-aro", descripcion: "Rango de movimiento mayor", musculo: "Pecho" },
    { nombre: "Aperturas con mancuernas", aliases: ["cruces mancuernas", "aberturas", "flies", "flyes"], youtube: "https://youtube.com/watch?v=eozdVDA78K0", descripcion: "Estiramiento del pecho", musculo: "Pecho" },
    { nombre: "Aperturas en polea", aliases: ["cruces en polea", "cable crossover", "cruce de poleas"], youtube: "https://youtube.com/watch?v=TAn4psGgEyc", descripcion: "Tensión constante", musculo: "Pecho" },
    { nombre: "Fondos en paralelas", aliases: ["dips", "fondos", "paralelas"], youtube: "https://youtube.com/watch?v=2z8JmcrW-As", descripcion: "Pecho y tríceps", musculo: "Pecho" },
    { nombre: "Pullover con mancuerna", aliases: ["pullover"], youtube: "https://youtube.com/watch?v=FK4rHfPuJgo", descripcion: "Expansión torácica", musculo: "Pecho" },
    { nombre: "Press en máquina", aliases: ["press maquina pecho", "maquina pecho"], youtube: "https://youtube.com/watch?v=xUm0BiZCX_I", descripcion: "Seguro para principiantes", musculo: "Pecho" },
    { nombre: "Flexiones", aliases: ["lagartijas", "push ups", "pushups"], youtube: "https://youtube.com/watch?v=IODxDxX7oi4", descripcion: "Sin equipamiento", musculo: "Pecho" },
  ],
  "Espalda": [
    { nombre: "Dominadas", aliases: ["pull ups", "pullups", "jalones con peso corporal"], youtube: "https://youtube.com/watch?v=eGo4IYlbE5g", descripcion: "Rey de los jalones", musculo: "Espalda" },
    { nombre: "Remo con barra", aliases: ["remo barra", "remo inclinado"], youtube: "https://youtube.com/watch?v=9efgcAjQe7E", descripcion: "Masa en espalda media", musculo: "Espalda" },
    { nombre: "Remo con mancuerna", aliases: ["remo mancuerna", "remo unilateral"], youtube: "https://youtube.com/watch?v=pYcpY20QaE8", descripcion: "Unilateral", musculo: "Espalda" },
    { nombre: "Jalón al pecho", aliases: ["jalon", "jalon polea", "jalón frontal", "lat pulldown"], youtube: "https://youtube.com/watch?v=CAwf7n6Luuc", descripcion: "Alternativa a dominadas", musculo: "Espalda" },
    { nombre: "Remo en polea baja", aliases: ["remo polea", "remo sentado", "remo cable"], youtube: "https://youtube.com/watch?v=GZbfZ033f74", descripcion: "Espalda media y baja", musculo: "Espalda" },
    { nombre: "Peso muerto", aliases: ["deadlift", "peso muerto convencional"], youtube: "https://youtube.com/watch?v=op9kVnSso6Q", descripcion: "Ejercicio global", musculo: "Espalda" },
    { nombre: "Peso muerto rumano", aliases: ["rdl", "peso muerto piernas semi-extendidas"], youtube: "https://youtube.com/watch?v=JCXUYuzwNrM", descripcion: "Isquiotibiales y espalda baja", musculo: "Espalda" },
    { nombre: "Hiperextensiones", aliases: ["extensiones lumbares", "back extension"], youtube: "https://youtube.com/watch?v=ph3pddpKzzw", descripcion: "Espalda baja", musculo: "Espalda" },
    { nombre: "Remo en máquina", aliases: ["remo maquina", "maquina remo"], youtube: "https://youtube.com/watch?v=xQNrFHEMhI4", descripcion: "Seguro y efectivo", musculo: "Espalda" },
    { nombre: "Pullover en polea", aliases: ["pullover polea", "pullover cable"], youtube: "https://youtube.com/watch?v=wMQ8t2gHxGs", descripcion: "Dorsal largo", musculo: "Espalda" },
  ],
  "Hombros": [
    { nombre: "Press militar con barra", aliases: ["press militar", "overhead press", "ohp"], youtube: "https://youtube.com/watch?v=2yjwXTZQDDI", descripcion: "Hombro completo", musculo: "Hombros" },
    { nombre: "Press Arnold", aliases: ["arnold press"], youtube: "https://youtube.com/watch?v=6Z15_WdXmVw", descripcion: "Rotación completa", musculo: "Hombros" },
    { nombre: "Press con mancuernas sentado", aliases: ["press hombros mancuernas", "press hombro"], youtube: "https://youtube.com/watch?v=qEwKCR5JCog", descripcion: "Hombro anterior y medio", musculo: "Hombros" },
    { nombre: "Elevaciones laterales", aliases: ["vuelos laterales", "lateral raises", "laterales"], youtube: "https://youtube.com/watch?v=3VcKaXpzqRo", descripcion: "Hombro lateral", musculo: "Hombros" },
    { nombre: "Elevaciones frontales", aliases: ["vuelos frontales", "frontales", "front raises"], youtube: "https://youtube.com/watch?v=sOoBSE-PrzQ", descripcion: "Hombro anterior", musculo: "Hombros" },
    { nombre: "Pájaros", aliases: ["vuelos posteriores", "vuelos inclinados", "reverse flies", "rear delt flies"], youtube: "https://youtube.com/watch?v=ttvAXDVDlBE", descripcion: "Hombro posterior", musculo: "Hombros" },
    { nombre: "Face pulls", aliases: ["jalón al rostro", "face pull polea"], youtube: "https://youtube.com/watch?v=rep-qVOkqgk", descripcion: "Manguito rotador", musculo: "Hombros" },
    { nombre: "Encogimientos con barra", aliases: ["encogimientos", "shrugs", "trapecios"], youtube: "https://youtube.com/watch?v=g6qbq4Lf1FI", descripcion: "Trapecio", musculo: "Hombros" },
    { nombre: "Press en máquina", aliases: ["press hombros maquina", "maquina hombros"], youtube: "https://youtube.com/watch?v=Wqq43dKW1TU", descripcion: "Guiado y seguro", musculo: "Hombros" },
    { nombre: "Remo al mentón", aliases: ["remo al menton", "upright row"], youtube: "https://youtube.com/watch?v=OwSuHjTmqHs", descripcion: "Trapecio y hombro", musculo: "Hombros" },
  ],
  "Piernas": [
    { nombre: "Sentadilla con barra", aliases: ["sentadilla", "squat", "back squat"], youtube: "https://youtube.com/watch?v=ultWZbUMPL8", descripcion: "Reina de los ejercicios", musculo: "Piernas" },
    { nombre: "Sentadilla frontal", aliases: ["front squat", "sentadilla delantera"], youtube: "https://youtube.com/watch?v=m4ytaCJZpl0", descripcion: "Cuádriceps dominante", musculo: "Piernas" },
    { nombre: "Sentadilla búlgara", aliases: ["sentadilla bulgara", "split squat", "zancada bulgara"], youtube: "https://youtube.com/watch?v=2C-uNgKwPLE", descripcion: "Unilateral avanzado", musculo: "Piernas" },
    { nombre: "Prensa de piernas", aliases: ["prensa", "leg press"], youtube: "https://youtube.com/watch?v=IZxyjW7MPJQ", descripcion: "Cuádriceps y glúteos", musculo: "Piernas" },
    { nombre: "Extensiones de cuádriceps", aliases: ["extensiones de piernas", "leg extension", "cuadriceps maquina"], youtube: "https://youtube.com/watch?v=YyvSfVjQeL0", descripcion: "Aislamiento cuádriceps", musculo: "Piernas" },
    { nombre: "Curl femoral", aliases: ["curl de piernas", "femoral maquina", "leg curl", "isquiotibiales maquina"], youtube: "https://youtube.com/watch?v=1Tq3QdYUuHs", descripcion: "Aislamiento isquiotibiales", musculo: "Piernas" },
    { nombre: "Peso muerto rumano", aliases: ["rdl", "peso muerto piernas"], youtube: "https://youtube.com/watch?v=JCXUYuzwNrM", descripcion: "Isquiotibiales y glúteos", musculo: "Piernas" },
    { nombre: "Zancadas", aliases: ["estocadas", "lunges", "zancada"], youtube: "https://youtube.com/watch?v=D7KaRcUTQeE", descripcion: "Funcional y completo", musculo: "Piernas" },
    { nombre: "Hip thrust", aliases: ["empuje de cadera", "puente de gluteo", "hip thrust barra"], youtube: "https://youtube.com/watch?v=xDmFkJxPzeM", descripcion: "Glúteo máximo", musculo: "Piernas" },
    { nombre: "Pantorrillas de pie", aliases: ["gemelos de pie", "calf raises", "pantorrillas"], youtube: "https://youtube.com/watch?v=-M4-G8p1fCI", descripcion: "Gastrocnemio", musculo: "Piernas" },
    { nombre: "Pantorrillas sentado", aliases: ["gemelos sentado", "soleo", "sóleo maquina"], youtube: "https://youtube.com/watch?v=JbyjNymZOt0", descripcion: "Sóleo", musculo: "Piernas" },
    { nombre: "Sentadilla sumo", aliases: ["sumo squat", "sentadilla pies abiertos"], youtube: "https://youtube.com/watch?v=U3HlEF_E9fo", descripcion: "Aductores y glúteos", musculo: "Piernas" },
  ],
  "Bíceps": [
    { nombre: "Curl con barra", aliases: ["curl barra", "rosca directa", "rosca barra"], youtube: "https://youtube.com/watch?v=ykJmrZ5v0Oo", descripcion: "Base del bíceps", musculo: "Bíceps" },
    { nombre: "Curl con mancuernas", aliases: ["rosca mancuernas", "curl mancuernas", "rosca alternada"], youtube: "https://youtube.com/watch?v=av7-8igSXTs", descripcion: "Rango completo", musculo: "Bíceps" },
    { nombre: "Curl martillo", aliases: ["rosca martillo", "hammer curl"], youtube: "https://youtube.com/watch?v=TwD-YGVP4Bk", descripcion: "Braquial y braquiorradial", musculo: "Bíceps" },
    { nombre: "Curl concentrado", aliases: ["rosca concentrada", "concentration curl"], youtube: "https://youtube.com/watch?v=Jvj2wV0vOYU", descripcion: "Pico del bíceps", musculo: "Bíceps" },
    { nombre: "Curl en polea baja", aliases: ["rosca polea", "curl polea", "cable curl"], youtube: "https://youtube.com/watch?v=NFzTWp2qpiE", descripcion: "Tensión constante", musculo: "Bíceps" },
    { nombre: "Curl predicador", aliases: ["rosca predicador", "predicador", "scott curl"], youtube: "https://youtube.com/watch?v=fIWP-FRFNU0", descripcion: "Elimina el balanceo", musculo: "Bíceps" },
    { nombre: "Curl inclinado", aliases: ["rosca inclinada", "incline curl"], youtube: "https://youtube.com/watch?v=soxrZlIl35U", descripcion: "Estiramiento máximo", musculo: "Bíceps" },
    { nombre: "Curl inverso", aliases: ["rosca inversa", "reverse curl"], youtube: "https://youtube.com/watch?v=nRgxYX2Ve9w", descripcion: "Braquiorradial", musculo: "Bíceps" },
  ],
  "Tríceps": [
    { nombre: "Press francés", aliases: ["skull crusher", "press frances", "rompecraneos"], youtube: "https://youtube.com/watch?v=d_KZxkY_0cM", descripcion: "Cabeza larga del tríceps", musculo: "Tríceps" },
    { nombre: "Extensión en polea alta", aliases: ["extension triceps polea", "polea triceps", "pushdown", "press down"], youtube: "https://youtube.com/watch?v=2-LAMcpzODU", descripcion: "Aislamiento total", musculo: "Tríceps" },
    { nombre: "Fondos en paralelas", aliases: ["dips triceps", "fondos triceps"], youtube: "https://youtube.com/watch?v=2z8JmcrW-As", descripcion: "Tríceps y pecho", musculo: "Tríceps" },
    { nombre: "Patada de tríceps", aliases: ["patada triceps", "kickback", "extensión con mancuerna"], youtube: "https://youtube.com/watch?v=6SS6K3lAwZ8", descripcion: "Definición", musculo: "Tríceps" },
    { nombre: "Press cerrado", aliases: ["press agarre cerrado", "close grip bench", "press agarre estrecho"], youtube: "https://youtube.com/watch?v=nEF0bv2FW94", descripcion: "Tríceps con barra", musculo: "Tríceps" },
    { nombre: "Extensión sobre la cabeza", aliases: ["extension sobre cabeza", "overhead triceps extension", "francés sobre la cabeza"], youtube: "https://youtube.com/watch?v=YbX7Wd8jQ-Q", descripcion: "Cabeza larga", musculo: "Tríceps" },
    { nombre: "Fondos en banco", aliases: ["dips banco", "triceps banco"], youtube: "https://youtube.com/watch?v=0326dy_-CzM", descripcion: "Sin equipamiento", musculo: "Tríceps" },
    { nombre: "Extensión en polea con cuerda", aliases: ["polea cuerda triceps", "extension cuerda", "rope pushdown"], youtube: "https://youtube.com/watch?v=kiuVA0gs3EI", descripcion: "Separación de cabezas", musculo: "Tríceps" },
  ],
  "Core": [
    { nombre: "Plancha", aliases: ["plank", "isometrico abdominal"], youtube: "https://youtube.com/watch?v=pSHjTRCQxIw", descripcion: "Estabilización total", musculo: "Core" },
    { nombre: "Crunch", aliases: ["abdominal", "abdominales", "crunch basico"], youtube: "https://youtube.com/watch?v=Xyd_fa5zoEU", descripcion: "Abdomen superior", musculo: "Core" },
    { nombre: "Crunch inverso", aliases: ["crunch invertido", "abdominales inferiores", "reverse crunch"], youtube: "https://youtube.com/watch?v=hyv14_1QMOA", descripcion: "Abdomen inferior", musculo: "Core" },
    { nombre: "Russian twist", aliases: ["giro ruso", "oblicuos rotación"], youtube: "https://youtube.com/watch?v=wkD8rjkodUI", descripcion: "Oblicuos", musculo: "Core" },
    { nombre: "Rueda abdominal", aliases: ["rueda ab", "ab wheel", "rueda de abdominales"], youtube: "https://youtube.com/watch?v=sNyOPxNVDDo", descripcion: "Core completo avanzado", musculo: "Core" },
    { nombre: "Elevación de piernas", aliases: ["elevacion piernas colgado", "leg raises", "tijeras"], youtube: "https://youtube.com/watch?v=JB2oyawG9KI", descripcion: "Abdomen inferior", musculo: "Core" },
    { nombre: "Mountain climbers", aliases: ["escaladores", "montañero"], youtube: "https://youtube.com/watch?v=nmwgirgXLYM", descripcion: "Cardio y core", musculo: "Core" },
    { nombre: "Dead bug", aliases: ["insecto muerto", "estabilizacion lumbar"], youtube: "https://youtube.com/watch?v=4XLEnwUr1d8", descripcion: "Estabilización lumbar", musculo: "Core" },
    { nombre: "Plancha lateral", aliases: ["plank lateral", "side plank"], youtube: "https://youtube.com/watch?v=K2VljzCC16g", descripcion: "Oblicuos", musculo: "Core" },
    { nombre: "Hollow body", aliases: ["hollow hold", "cuerpo hueco"], youtube: "https://youtube.com/watch?v=LlDNef_Ztsc", descripcion: "Core funcional", musculo: "Core" },
  ],
  "Glúteos": [
    { nombre: "Hip thrust", aliases: ["puente gluteo", "empuje cadera", "hip thrust barra"], youtube: "https://youtube.com/watch?v=xDmFkJxPzeM", descripcion: "Rey del glúteo", musculo: "Glúteos" },
    { nombre: "Patada de glúteo", aliases: ["patada trasera", "kickback gluteo", "donkey kick"], youtube: "https://youtube.com/watch?v=FdWHhItkfko", descripcion: "Aislamiento", musculo: "Glúteos" },
    { nombre: "Abducción de cadera", aliases: ["abduccion", "maquina abductora", "aductora"], youtube: "https://youtube.com/watch?v=MFSKnJg7GU8", descripcion: "Glúteo medio", musculo: "Glúteos" },
    { nombre: "Sentadilla sumo", aliases: ["sumo squat gluteo", "sentadilla pies abiertos"], youtube: "https://youtube.com/watch?v=U3HlEF_E9fo", descripcion: "Glúteos y aductores", musculo: "Glúteos" },
    { nombre: "Zancada reversa", aliases: ["zancada hacia atras", "reverse lunge"], youtube: "https://youtube.com/watch?v=xrPteyQLGAo", descripcion: "Glúteo y cuádriceps", musculo: "Glúteos" },
    { nombre: "Buenos días", aliases: ["good morning", "buenos dias barra"], youtube: "https://youtube.com/watch?v=YA-h3n9L4YU", descripcion: "Glúteo e isquiotibiales", musculo: "Glúteos" },
  ],
  "Cardio": [
    { nombre: "Cinta a intervalos", aliases: ["running intervalos", "hiit cinta", "trotadora"], youtube: "https://youtube.com/watch?v=7kgZnJSzROE", descripcion: "HIIT en cinta", musculo: "Cardio" },
    { nombre: "Bicicleta estática", aliases: ["bicicleta fija", "cycling", "spinning"], youtube: "https://youtube.com/watch?v=RKM8BHjUFXk", descripcion: "Bajo impacto", musculo: "Cardio" },
    { nombre: "Remo ergómetro", aliases: ["remo maquina cardio", "rowing machine", "concept2"], youtube: "https://youtube.com/watch?v=zQ82RYIFLN4", descripcion: "Cuerpo completo", musculo: "Cardio" },
    { nombre: "Salto a la soga", aliases: ["saltar a la cuerda", "jump rope", "soga"], youtube: "https://youtube.com/watch?v=FJmRQ5iTXKE", descripcion: "Coordinación y cardio", musculo: "Cardio" },
    { nombre: "Burpees", aliases: ["burpee"], youtube: "https://youtube.com/watch?v=dZgVxmf6jkA", descripcion: "Funcional intenso", musculo: "Cardio" },
    { nombre: "Box jumps", aliases: ["salto al cajón", "salto a la caja", "saltos pliometricos"], youtube: "https://youtube.com/watch?v=hxldG9FBEAo", descripcion: "Potencia explosiva", musculo: "Cardio" },
  ],
}

// Mapa de términos coloquiales de músculo a clave del objeto
export const MUSCULO_ALIASES = {
  "biceps": "Bíceps", "bíceps": "Bíceps",
  "triceps": "Tríceps", "tríceps": "Tríceps", "tri": "Tríceps",
  "pecho": "Pecho", "chest": "Pecho", "pectorales": "Pecho",
  "espalda": "Espalda", "dorsal": "Espalda", "dorsales": "Espalda", "lats": "Espalda",
  "hombros": "Hombros", "hombro": "Hombros", "deltoides": "Hombros",
  "piernas": "Piernas", "cuadriceps": "Piernas", "cuádriceps": "Piernas", "femoral": "Piernas", "isquiotibiales": "Piernas",
  "gluteos": "Glúteos", "glúteos": "Glúteos", "gluteo": "Glúteos", "glúteo": "Glúteos", "cola": "Glúteos",
  "core": "Core", "abdomen": "Core", "abdominales": "Core", "abs": "Core",
  "cardio": "Cardio",
}
